/* DO NOT EDIT THIS FILE - it is machine generated or manually maintained */
/*
 * PipeWire JNI bridge — JNI function declarations for PipeWireCaptureJniBridge.kt
 *
 * Mirrors the AudioCaptureBridgeJNI.h contract for the Linux PipeWire backend.
 */
#ifndef PIPEWIRE_CAPTURE_BRIDGE_JNI_H
#define PIPEWIRE_CAPTURE_BRIDGE_JNI_H

#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jboolean JNICALL
Java_com_meetingnotes_audio_PipeWireCaptureJniBridge_nativeIsAvailable(JNIEnv*, jobject);

JNIEXPORT jboolean JNICALL
Java_com_meetingnotes_audio_PipeWireCaptureJniBridge_nativeStartCapture(JNIEnv*, jobject, jint sampleRate);

JNIEXPORT jint JNICALL
Java_com_meetingnotes_audio_PipeWireCaptureJniBridge_nativeReadBuffer(JNIEnv*, jobject, jfloatArray buffer);

JNIEXPORT void JNICALL
Java_com_meetingnotes_audio_PipeWireCaptureJniBridge_nativeStopCapture(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif

#endif /* PIPEWIRE_CAPTURE_BRIDGE_JNI_H */
