/* DO NOT EDIT - generated by javah from ScreenCaptureJniBridge.kt */
#ifndef AudioCaptureBridgeJNI_h
#define AudioCaptureBridgeJNI_h

#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_meetingnotes_audio_ScreenCaptureJniBridge
 * Method:    nativeCheckPermission
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_meetingnotes_audio_ScreenCaptureJniBridge_nativeCheckPermission(JNIEnv *, jobject);

/*
 * Class:     com_meetingnotes_audio_ScreenCaptureJniBridge
 * Method:    nativeRequestPermission
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_meetingnotes_audio_ScreenCaptureJniBridge_nativeRequestPermission(JNIEnv *, jobject);

/*
 * Class:     com_meetingnotes_audio_ScreenCaptureJniBridge
 * Method:    nativeStartCapture
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_meetingnotes_audio_ScreenCaptureJniBridge_nativeStartCapture(JNIEnv *, jobject, jint);

/*
 * Class:     com_meetingnotes_audio_ScreenCaptureJniBridge
 * Method:    nativeStopCapture
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_meetingnotes_audio_ScreenCaptureJniBridge_nativeStopCapture(JNIEnv *, jobject);

/*
 * Class:     com_meetingnotes_audio_ScreenCaptureJniBridge
 * Method:    nativeReadBuffer
 * Signature: ([F)I
 */
JNIEXPORT jint JNICALL Java_com_meetingnotes_audio_ScreenCaptureJniBridge_nativeReadBuffer(JNIEnv *, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif

#endif /* AudioCaptureBridgeJNI_h */
